Repository amir-kedis/Kashafty, pull requests merged in 2024-09, with the labels that each got.

#75 fix: connect arabicErrors from backend with frontend
  client/src/components/addactivitypage/AddActivityPage.tsx
  client/src/components/assign-captain-page/AssignSector.tsx
  client/src/components/assign-captain-page/ChangeCaptainType.tsx
  client/src/components/assign-captain-page/UnitAssignSector.tsx
  client/src/components/cancel-week/CancelWeek.tsx
  client/src/components/captains-attendance/CaptainAttendance.tsx
  client/src/components/common/nav.tsx
  client/src/components/edit-password/EditPassword.tsx
  client/src/components/insert-scout/InsertScoutPage.tsx
  client/src/components/insert-sector/InsertSector.tsx
  client/src/components/insert-term/InsertTermPage.tsx
  client/src/components/login/logIn.tsx
  client/src/components/moneypage/MoneyPage.tsx
  client/src/components/scouts-attendance/ScoutsAttendance.tsx
  client/src/components/send-notification/sendNotificationPage.tsx
  client/src/components/signup/signUp.tsx
  client/src/components/update-scout/UpdateScoutPage.tsx
  client/src/components/update-term-page/UpdateTermPage.tsx
Labels: bug, enhancement

#77 :test_tube: end-to-end testing setup + specs for auth functionality
  client/cypress.config.ts
  client/cypress/e2e/auth/login.cy.js
  client/cypress/e2e/auth/signup.cy.js
  client/cypress/fixtures/example.json
  client/cypress/fixtures/profile.json
  client/cypress/fixtures/users.json
  client/cypress/support/commands.ts
  client/cypress/support/e2e.ts
  client/package-lock.json
  client/package.json
  server/prisma/scouts-csv-archive/جوالة أ.csv
  server/prisma/scouts-csv/براعم أ.csv
Labels: enhancement

#79 Scout changes
  client/src/types/prismaTypes.ts
  server/controllers/cron.controller.ts
  server/controllers/scout.controller.ts
  server/controllers/stat/stat.attendance.controller.ts
  server/database/db.ts
  server/database/scheduler.ts
  server/prisma/import-scouts.ts
  server/prisma/schema.prisma
  server/prisma/seed.ts
  server/routes/scout.route.ts
  server/utils/getScoutsByName.ts
Labels: DB, backend

#86 devops: enhance docker developer experience and setup coolify home server production setup
  .env.example
  .gitignore
  README.md
  client/.dockerignore
  client/.env.development.example
  client/.env.production.exmaple
  client/Dockerfile
  client/Dockerfile.dev
  client/Dockerfile.prod
  client/nginx.conf
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/vite.config.ts
  docker-compose.prod.yml
  docker-compose.yml
  server/.env.example
  server/Dockerfile
  server/Dockerfile.dev
  server/Dockerfile.prod
  server/index.ts
  server/package.json
Labels: feature, devops
